package com.redis.workshop.search.service;

import com.redis.workshop.search.domain.Movie;
// import com.redis.workshop.search.repository.MovieRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.*;
import java.util.stream.Collectors;

// TODO: Uncomment these imports after adding Redis OM Spring dependency
// import com.redis.workshop.search.domain.Movie$;
// import com.redis.om.spring.search.stream.EntityStream;
// import com.redis.om.spring.search.stream.SearchStream;

// import static redis.clients.jedis.search.aggr.SortedField.SortOrder.DESC;

/**
 * Service for performing full-text search operations on movies.
 *
 * Uses Redis OM Spring's EntityStream API for building search queries.
 * The Movie$ class is auto-generated by the annotation processor and provides
 * type-safe field references for query building.
 */
@Service
public class SearchService {

    private static final Logger logger = LoggerFactory.getLogger(SearchService.class);
    // TODO: Uncomment these fields after adding Redis OM Spring dependency
    // private final EntityStream entityStream;
    // private final MovieRepository movieRepository;

    // TODO: Update constructor to inject EntityStream and MovieRepository after adding Redis OM Spring
    public SearchService(/* EntityStream entityStream, MovieRepository movieRepository */) {
        // this.entityStream = entityStream;
        // this.movieRepository = movieRepository;
    }

    public Map<String, Object> searchMovies(
            String title,
            String extract,
            List<String> actors,
            Integer year,
            List<String> genres
    ) {
        logger.info("Searching - title: {}, extract: {}, cast: {}, year: {}, genres: {}",
                title, extract, actors, year, genres);

        long startTime = System.currentTimeMillis();

        // TODO: Implement search using EntityStream
        // SearchStream<Movie> stream = entityStream.of(Movie.class);
        //
        // Build the search query with filters
        // containing() - full-text search on @Searchable fields
        // eq() - exact match on @Indexed fields
        // List<Movie> matchedMovies = stream
        //         .filter(Movie$.TITLE.containing(title))
        //         .filter(Movie$.EXTRACT.containing(extract))
        //         .filter(Movie$.CAST.eq(actors))
            //         .filter(Movie$.YEAR.eq(year))
            //         .filter(Movie$.GENRES.eq(genres))
            //         .sorted(Movie$.YEAR, DESC)
            //         .collect(Collectors.toList());

        // Temporary: Return empty results until Redis OM Spring is configured
        List<Movie> matchedMovies = new ArrayList<>();
        long searchTime = System.currentTimeMillis() - startTime;

        logger.info("Search completed in {} ms, found {} movies", searchTime, matchedMovies.size());

        Map<String, Object> result = new HashMap<>();
        result.put("movies", matchedMovies);
        result.put("count", matchedMovies.size());
        result.put("searchTime", searchTime);

        return result;
    }

    public Set<String> getAllGenres() {
        logger.info("Fetching all unique genres");
        long startTime = System.currentTimeMillis();

        // TODO: Uncomment after implementing MovieRepository
        // Iterable<String> genresIterable = movieRepository.getAllGenres();
        // Set<String> allGenres = new HashSet<>();
        // genresIterable.forEach(allGenres::add);

        // Temporary: Return empty set until Redis OM Spring is configured
        Set<String> allGenres = new HashSet<>();
        long fetchTime = System.currentTimeMillis() - startTime;

        logger.info("Fetched {} unique genres in {} ms", allGenres.size(), fetchTime);

        return allGenres;
    }
}
